### ISSUE TITLE
Using spread will mess up the aspect ratio of the shadow

### ISSUE THREAD

**Issue by christoph-hart** [sudara/melatonin_blur#59]
I'm writing a CSS renderer in JUCE and your blur module does the job almost perfectly. However the following CSS code:

```css
{
	background: #666;
	height: 80px;
	margin: 20px;
	border: 5px solid green;
	box-shadow: 0px 0px 0px  5px    red;	
        /*          x   y   blur spread color */
}
```

renders this output:

![image](https://github.com/sudara/melatonin_blur/assets/6277426/ff57a87c-d065-4aec-b256-0072cbe8a102)

This is because it retains the aspect ratio of the path when using spread. If I change the scaling to not preserve the aspect ratio by passing in `false` as last parameter here:

https://github.com/sudara/melatonin_blur/blob/ae44478ff6de763551923c37afb0c81ea96243a8/melatonin/internal/rendered_single_channel_shadow.cpp#L28

I get this beauty:

![image](https://github.com/sudara/melatonin_blur/assets/6277426/b8e83a3f-b175-412a-86c1-ffad2bf6f738)

Is there a reason why you retain the aspect ratio of the path when scaling up? Looks good with a square, not so good with any other shape :)
